name: "Scan secrets"
description: "Scan secrets"
runs:
  using: "composite"
  steps:
    - name: "Scan secrets"
      shell: bash
      run: |
        # To be certain that nothing slips into the history, switch to `check=whole-history`
        check=branch-changes ./scripts/githooks/scan-secrets.sh
