name: "Scan secrets"
description: "Scan secrets"
runs:
  using: "composite"
  steps:
    - name: "Scan secrets"
      shell: bash
      run: |
        # Please do not change this `check=whole-history` setting, as new patterns may be added or history may be rewritten.
        check=whole-history ./scripts/githooks/scan-secrets.sh
