#!/bin/bash
# shellcheck disable=SC1091,SC2154

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Shell script linter.
#
# Usage:
#   $ ./shellscript-linter.sh
#
# Arguments (provided as environment variables):
#   file=shellscript  # Path to the shell script to lint, relative to the project top-level directory
#   VERBOSE=true      # Show all the executed commands, default is 'false'

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"
  source ./scripts/docker/docker.lib.sh
  docker-run-shellcheck
}

function docker-run-shellcheck() {

  image=$(name=koalaman/shellcheck docker-get-image-version-and-pull)
  docker run --rm --platform linux/amd64 \
    --volume "$PWD:/workdir" \
    "$image" \
      "/workdir/$file"
}

# ==============================================================================

function is_arg_true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is_arg_true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
