#!/bin/bash

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Pre-commit git hook to scan for secrets hardcoded in the codebase.
#
# Usage:
#   $ check={whole-history,last-commit,staged-changes} ./scan-secrets.sh
#
# Options:
#   VERBOSE=true  # Show all the executed commands, default is `false`
#
# Exit codes:
#   0 - No leaks present
#   1 - Leaks or error encountered
#   126 - Unknown flag

# ==============================================================================

# SEE: https://github.com/gitleaks/gitleaks/pkgs/container/gitleaks, use the `linux/amd64` os/arch
image_version=v8.18.0@sha256:fd2b5cab12b563d2cc538b14631764a1c25577780e3b7dba71657d58da45d9d9

# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  check=${check:-staged-changes}
  case $check in
    "whole-history")
      cmd="detect --source /scan --verbose --redact"
      ;;
    "last-commit")
      cmd="detect --source /scan --verbose --redact --log-opts -1"
      ;;
    "staged-changes")
      cmd="protect --source /scan --verbose --staged"
      ;;
  esac
  # Include base line file if it exists
  if [ -f "$PWD/scripts/config/.gitleaks-baseline.json" ]; then
    cmd="$cmd --baseline-path /scan/scripts/config/.gitleaks-baseline.json"
  fi

  # shellcheck disable=SC2086
  docker run --rm --platform linux/amd64 \
    --volume "$PWD":/scan \
    --workdir /scan \
    ghcr.io/gitleaks/gitleaks:$image_version \
      $cmd \
      --config /scan/scripts/config/gitleaks.toml
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
